name: Stock Alert
on:
  schedule:
    - cron: '0 10 * * 1-5'  # Runs at 10:00 UTC (3:30 PM IST) on weekdays

jobs:
  send-alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run alert script
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python stock_alerts.py
